// =============================================================================
// ADOPTION DASHBOARD v5.1 — DAX Measures
// =============================================================================
// All measures derived directly from the Excel v5.1 workbook formulas.
//
// TABLE NAMES (must match exactly in Power BI):
//   Data           — main fact table (from Power Query "Data")
//   FiscalCalendar — from Power Query "FiscalCalendar"
//   PVI_Brackets   — from Power Query "PVI_Brackets"
//
// HOW TO USE:
//   1. Create a new table: Enter Data → name it "_Measures", leave it empty.
//   2. For each measure below, select the _Measures table and click New Measure.
//   3. Paste the DAX expression (everything after "=").
//
// IMPORTANT NOTES ON DEDUP PATTERN:
//   The Overview formula logic uses UNIQUE(CRPartyID-Offer) + MAXIFS per pair.
//   In DAX this becomes: SUMMARIZE filtered rows → MAXX per group → SUMX.
//   The filter context from slicers/matrix rows is handled automatically.
//
// DISTRIBUTOR MODE:
//   In Excel, PVI formulas check Input_region <> "DISTI".
//   In Power BI, add a "Mode" What-If Parameter (Partner / Distributor) and
//   reference [Mode Value] in PVI measures (see PVI section below).
// =============================================================================


// =============================================================================
// SECTION 1 — OVERVIEW PAGE MEASURES  (columns E through Q)
// =============================================================================

// ── Col E: Total UC Eligible w/o opt-in (unique customer count) ──────────────
// Excel: ROWS(UNIQUE(FILTER(Data[CR Party ID], SubTrack + NOT opted-in + Eligible)))
[UC Eligible w/o Opt-In] =
CALCULATE(
    DISTINCTCOUNT( Data[CR Party ID] ),
    Data[Offer opted-in?] = FALSE(),
    Data[Stage] = "Eligible"
)

// ── Col F: Total Potential Incentives (max per CRPartyID-Offer, deduped) ─────
// Excel: SUMX(BYROW(UNIQUE(CRPartyID-Offer pairs), MAXIFS(Potential Incentives)))
// Filters: same Offer+SubTrack+Stage=Eligible+NOT opted-in
[Total Potential Incentives] =
SUMX(
    SUMMARIZE(
        CALCULATETABLE(
            Data,
            Data[Offer opted-in?] = FALSE(),
            Data[Stage] = "Eligible"
        ),
        Data[CRPartyID-Offer]
    ),
    CALCULATE(
        MAX( Data[Potential Incentives] ),
        Data[Offer opted-in?] = FALSE(),
        Data[Stage] = "Eligible"
    )
)

// ── Col G: UC 25-50% eligible w/o opt-in (unique customer count) ─────────────
[UC 25-50% w/o Opt-In] =
CALCULATE(
    DISTINCTCOUNT( Data[CR Party ID] ),
    Data[UC 25-50% eligible w/o opt-in] = TRUE()
)

// ── Col H: Potential Incentives (25-50%, max per CRPartyID-Offer) ────────────
[Potential Incentives 25-50%] =
SUMX(
    SUMMARIZE(
        CALCULATETABLE( Data, Data[UC 25-50% eligible w/o opt-in] = TRUE() ),
        Data[CRPartyID-Offer]
    ),
    CALCULATE(
        MAX( Data[Potential Incentives] ),
        Data[UC 25-50% eligible w/o opt-in] = TRUE()
    )
)

// ── Col I: UC 75% eligible w/o opt-in (unique customer count) ────────────────
[UC 75% w/o Opt-In] =
CALCULATE(
    DISTINCTCOUNT( Data[CR Party ID] ),
    Data[UC 75% eligible w/o opt-in] = TRUE()
)

// ── Col J: Missed Incentives (75%, max per CRPartyID-Offer) ──────────────────
[Missed Incentives 75%] =
SUMX(
    SUMMARIZE(
        CALCULATETABLE( Data, Data[UC 75% eligible w/o opt-in] = TRUE() ),
        Data[CRPartyID-Offer]
    ),
    CALCULATE(
        MAX( Data[Missed Incentives] ),
        Data[UC 75% eligible w/o opt-in] = TRUE()
    )
)

// ── Col K: Potential Incentives (75%, max per CRPartyID-Offer) ───────────────
[Potential Incentives 75%] =
SUMX(
    SUMMARIZE(
        CALCULATETABLE( Data, Data[UC 75% eligible w/o opt-in] = TRUE() ),
        Data[CRPartyID-Offer]
    ),
    CALCULATE(
        MAX( Data[Potential Incentives] ),
        Data[UC 75% eligible w/o opt-in] = TRUE()
    )
)

// ── Col L: UC progressed and missed w/o opt-in (unique customer count) ───────
[UC Progressed and Missed] =
CALCULATE(
    DISTINCTCOUNT( Data[CR Party ID] ),
    Data[UC progressed and missed w/o opt-in] = TRUE()
)

// ── Col M: Missed Incentives (progressed+missed, max per CRPartyID-Offer) ────
[Missed Incentives Progressed] =
SUMX(
    SUMMARIZE(
        CALCULATETABLE( Data, Data[UC progressed and missed w/o opt-in] = TRUE() ),
        Data[CRPartyID-Offer]
    ),
    CALCULATE(
        MAX( Data[Missed Incentives] ),
        Data[UC progressed and missed w/o opt-in] = TRUE()
    )
)

// ── Col N: Active Opted-in UC (row count) ────────────────────────────────────
// Excel: SUM of condition (Sub-Track match + "Opted in" + Stage=Eligible)
// Note: Excel uses "Opted in" (lowercase i) — match exactly
[Active Opted-In UC] =
CALCULATE(
    COUNTROWS( Data ),
    Data[Adopt Rebate Opt-In Status] = "Opted In",
    Data[Stage] = "Eligible"
)

// ── Col O: Potential Incentives (opted-in, eligible) ─────────────────────────
[Potential Incentives Opted-In] =
CALCULATE(
    SUM( Data[Potential Incentives] ),
    Data[Adopt Rebate Opt-In Status] = "Opted In",
    Data[Stage] = "Eligible"
)

// ── Col P: Progressed opted-in UC (row count) ────────────────────────────────
// Excel: SUM of condition (Sub-Track match + Earned?=TRUE)
[Progressed Opted-In UC] =
CALCULATE(
    COUNTROWS( Data ),
    Data[Earned?] = TRUE()
)

// ── Col Q: Estimated Earned Incentives ───────────────────────────────────────
// Excel: simple SUM filtered by Sub-Track
[Estimated Earned Incentives] =
SUM( Data[Estimated Earned Incentives] )


// =============================================================================
// SECTION 2 — DETAILS PAGE MEASURES
// =============================================================================

// Customer count = distinct CR Party IDs in current filter context
[Customer Count] =
DISTINCTCOUNT( Data[CR Party ID] )

// Use case count = distinct CR Party ID + Offer combinations
// Excel: UNIQUE(CR Party ID & "|" & Offer) then COUNTA minus blanks
[Use Case Count] =
DISTINCTCOUNT( Data[CRPartyID-Offer] )

// Total Missed Incentives (MAXIFS per CR Party ID + Offer dedup)
// Excel: SUMX(BYROW(UNIQUE(CR Party ID + Offer pairs), MAXIFS(Missed)))
[Total Missed Incentives] =
SUMX(
    SUMMARIZE( Data, Data[CRPartyID-Offer] ),
    CALCULATE( MAX( Data[Missed Incentives] ) )
)

// Total Potential Incentives (same dedup pattern)
[Total Potential Incentives Summary] =
SUMX(
    SUMMARIZE( Data, Data[CRPartyID-Offer] ),
    CALCULATE( MAX( Data[Potential Incentives] ) )
)

// Total Estimated Earned (same dedup pattern)
[Total Estimated Earned Summary] =
SUMX(
    SUMMARIZE( Data, Data[CRPartyID-Offer] ),
    CALCULATE( MAX( Data[Estimated Earned Incentives] ) )
)


// =============================================================================
// SECTION 3 — PVI PAGE MEASURES
// =============================================================================
// Excel PVI formulas use Input_region <> "DISTI" to gate PVI display.
// In Power BI: create a What-If Parameter named "Partner Mode"
//   Values: "Partner" (default), "Distributor"
// Then wrap PVI measures with: IF([Partner Mode Value] = "Distributor", BLANK(), ...)
// For simplicity the measures below return BLANK() when no PVI-eligible rows exist.

// ── PVI Eligible — distinct CRPartyID-Offer count ────────────────────────────
// Excel: ROWS(UNIQUE(FILTER(CRPartyID-Offer, PVI Eligible=TRUE + Portfolio match)))
[PVI Eligible UC - Networking] =
CALCULATE(
    DISTINCTCOUNT( Data[CRPartyID-Offer] ),
    Data[PVI Eligible] = TRUE(),
    Data[Deal CPI Portfolio] = "Networking"
)

[PVI Eligible UC - Security] =
CALCULATE(
    DISTINCTCOUNT( Data[CRPartyID-Offer] ),
    Data[PVI Eligible] = TRUE(),
    Data[Deal CPI Portfolio] = "Security"
)

[PVI Eligible UC - Cloud] =
CALCULATE(
    DISTINCTCOUNT( Data[CRPartyID-Offer] ),
    Data[PVI Eligible] = TRUE(),
    Data[Deal CPI Portfolio] = "Cloud + AI Infrastructure"
)

// ── PVI Eligible Booking Value ────────────────────────────────────────────────
[PVI Eligible Booking - Networking] =
CALCULATE(
    SUM( Data[Booking Amount - Net to Cisco] ),
    Data[PVI Eligible] = TRUE(),
    Data[Deal CPI Portfolio] = "Networking"
)

[PVI Eligible Booking - Security] =
CALCULATE(
    SUM( Data[Booking Amount - Net to Cisco] ),
    Data[PVI Eligible] = TRUE(),
    Data[Deal CPI Portfolio] = "Security"
)

[PVI Eligible Booking - Cloud] =
CALCULATE(
    SUM( Data[Booking Amount - Net to Cisco] ),
    Data[PVI Eligible] = TRUE(),
    Data[Deal CPI Portfolio] = "Cloud + AI Infrastructure"
)

// ── PVI Onboarded (row count — Excel uses SUM of condition, not DISTINCTCOUNT) ─
// Excel: SUM((PVI Onboard=TRUE) * (Portfolio=domain))
[PVI Onboarded UC - Networking] =
CALCULATE(
    COUNTROWS( Data ),
    Data[PVI Onboard] = TRUE(),
    Data[Deal CPI Portfolio] = "Networking"
)

[PVI Onboarded UC - Security] =
CALCULATE(
    COUNTROWS( Data ),
    Data[PVI Onboard] = TRUE(),
    Data[Deal CPI Portfolio] = "Security"
)

[PVI Onboarded UC - Cloud] =
CALCULATE(
    COUNTROWS( Data ),
    Data[PVI Onboard] = TRUE(),
    Data[Deal CPI Portfolio] = "Cloud + AI Infrastructure"
)

// ── PVI Onboarded Booking Value ───────────────────────────────────────────────
[PVI Onboarded Booking - Networking] =
CALCULATE(
    SUM( Data[Booking Amount - Net to Cisco] ),
    Data[PVI Onboard] = TRUE(),
    Data[Deal CPI Portfolio] = "Networking"
)

[PVI Onboarded Booking - Security] =
CALCULATE(
    SUM( Data[Booking Amount - Net to Cisco] ),
    Data[PVI Onboard] = TRUE(),
    Data[Deal CPI Portfolio] = "Security"
)

[PVI Onboarded Booking - Cloud] =
CALCULATE(
    SUM( Data[Booking Amount - Net to Cisco] ),
    Data[PVI Onboard] = TRUE(),
    Data[Deal CPI Portfolio] = "Cloud + AI Infrastructure"
)

// ── PVI Onboard Ratio ─────────────────────────────────────────────────────────
// Excel: Onboarded UC / Eligible UC  (using count columns B vs B row 6/5)
[PVI Onboard Ratio - Networking] =
DIVIDE( [PVI Onboarded UC - Networking], [PVI Eligible UC - Networking] )

[PVI Onboard Ratio - Security] =
DIVIDE( [PVI Onboarded UC - Security], [PVI Eligible UC - Security] )

[PVI Onboard Ratio - Cloud] =
DIVIDE( [PVI Onboarded UC - Cloud], [PVI Eligible UC - Cloud] )

// ── PVI Adopted (row count) ───────────────────────────────────────────────────
[PVI Adopted UC - Networking] =
CALCULATE(
    COUNTROWS( Data ),
    Data[PVI Adopt] = TRUE(),
    Data[Deal CPI Portfolio] = "Networking"
)

[PVI Adopted UC - Security] =
CALCULATE(
    COUNTROWS( Data ),
    Data[PVI Adopt] = TRUE(),
    Data[Deal CPI Portfolio] = "Security"
)

[PVI Adopted UC - Cloud] =
CALCULATE(
    COUNTROWS( Data ),
    Data[PVI Adopt] = TRUE(),
    Data[Deal CPI Portfolio] = "Cloud + AI Infrastructure"
)

// ── PVI Adopted Booking Value ─────────────────────────────────────────────────
[PVI Adopted Booking - Networking] =
CALCULATE(
    SUM( Data[Booking Amount - Net to Cisco] ),
    Data[PVI Adopt] = TRUE(),
    Data[Deal CPI Portfolio] = "Networking"
)

[PVI Adopted Booking - Security] =
CALCULATE(
    SUM( Data[Booking Amount - Net to Cisco] ),
    Data[PVI Adopt] = TRUE(),
    Data[Deal CPI Portfolio] = "Security"
)

[PVI Adopted Booking - Cloud] =
CALCULATE(
    SUM( Data[Booking Amount - Net to Cisco] ),
    Data[PVI Adopt] = TRUE(),
    Data[Deal CPI Portfolio] = "Cloud + AI Infrastructure"
)

// ── PVI Adopt Ratio ───────────────────────────────────────────────────────────
// Excel: Adopted UC / Eligible UC (count / count, rows 9/5)
[PVI Adopt Ratio - Networking] =
DIVIDE( [PVI Adopted UC - Networking], [PVI Eligible UC - Networking] )

[PVI Adopt Ratio - Security] =
DIVIDE( [PVI Adopted UC - Security], [PVI Eligible UC - Security] )

[PVI Adopt Ratio - Cloud] =
DIVIDE( [PVI Adopted UC - Cloud], [PVI Eligible UC - Cloud] )

// ── PVI Scores — step lookup from PVI_Brackets ────────────────────────────────
// Excel: XLOOKUP(ratio, perc_array, score_array, 10, match_mode=1, search_mode=1)
// match_mode=1 = next larger item; search_mode=1 = first-to-last
// DAX equivalent: find the highest MinRatio that is <= the actual ratio,
// return that row's Score.  Default = 10 if ratio exceeds all thresholds.
[PVI Onboard Score - Networking] =
VAR Ratio = [PVI Onboard Ratio - Networking]
VAR Score =
    MAXX(
        FILTER(
            PVI_Brackets,
            PVI_Brackets[Domain] = "Networking"
                && PVI_Brackets[Metric] = "Onboard"
                && PVI_Brackets[MinRatio] <= Ratio
        ),
        PVI_Brackets[Score]
    )
RETURN IF( ISNUMBER(Ratio) && Ratio >= 0, COALESCE(Score, 10), BLANK() )

[PVI Onboard Score - Security] =
VAR Ratio = [PVI Onboard Ratio - Security]
VAR Score =
    MAXX(
        FILTER(
            PVI_Brackets,
            PVI_Brackets[Domain] = "Security"
                && PVI_Brackets[Metric] = "Onboard"
                && PVI_Brackets[MinRatio] <= Ratio
        ),
        PVI_Brackets[Score]
    )
RETURN IF( ISNUMBER(Ratio) && Ratio >= 0, COALESCE(Score, 10), BLANK() )

[PVI Onboard Score - Cloud] =
VAR Ratio = [PVI Onboard Ratio - Cloud]
VAR Score =
    MAXX(
        FILTER(
            PVI_Brackets,
            PVI_Brackets[Domain] = "Cloud + AI Infrastructure"
                && PVI_Brackets[Metric] = "Onboard"
                && PVI_Brackets[MinRatio] <= Ratio
        ),
        PVI_Brackets[Score]
    )
RETURN IF( ISNUMBER(Ratio) && Ratio >= 0, COALESCE(Score, 10), BLANK() )

[PVI Adopt Score - Networking] =
VAR Ratio = [PVI Adopt Ratio - Networking]
VAR Score =
    MAXX(
        FILTER(
            PVI_Brackets,
            PVI_Brackets[Domain] = "Networking"
                && PVI_Brackets[Metric] = "Adopt"
                && PVI_Brackets[MinRatio] <= Ratio
        ),
        PVI_Brackets[Score]
    )
RETURN IF( ISNUMBER(Ratio) && Ratio >= 0, COALESCE(Score, 10), BLANK() )

[PVI Adopt Score - Security] =
VAR Ratio = [PVI Adopt Ratio - Security]
VAR Score =
    MAXX(
        FILTER(
            PVI_Brackets,
            PVI_Brackets[Domain] = "Security"
                && PVI_Brackets[Metric] = "Adopt"
                && PVI_Brackets[MinRatio] <= Ratio
        ),
        PVI_Brackets[Score]
    )
RETURN IF( ISNUMBER(Ratio) && Ratio >= 0, COALESCE(Score, 10), BLANK() )

[PVI Adopt Score - Cloud] =
VAR Ratio = [PVI Adopt Ratio - Cloud]
VAR Score =
    MAXX(
        FILTER(
            PVI_Brackets,
            PVI_Brackets[Domain] = "Cloud + AI Infrastructure"
                && PVI_Brackets[Metric] = "Adopt"
                && PVI_Brackets[MinRatio] <= Ratio
        ),
        PVI_Brackets[Score]
    )
RETURN IF( ISNUMBER(Ratio) && Ratio >= 0, COALESCE(Score, 10), BLANK() )

// ── PVI Engagement Total ──────────────────────────────────────────────────────
// Excel: (Onboard Score + Adopt Score) / 2
[PVI Engagement Total - Networking] =
DIVIDE(
    [PVI Onboard Score - Networking] + [PVI Adopt Score - Networking],
    2
)

[PVI Engagement Total - Security] =
DIVIDE(
    [PVI Onboard Score - Security] + [PVI Adopt Score - Security],
    2
)

[PVI Engagement Total - Cloud] =
DIVIDE(
    [PVI Onboard Score - Cloud] + [PVI Adopt Score - Cloud],
    2
)

// ── PVI Simulation Measures ───────────────────────────────────────────────────
// These use What-If Parameters.  In Power BI, create two parameters:
//   "Sim Onboard Booking NET"  (min 0, max = large number, increment = 1000)
//   "Sim Adopt Booking NET"    (similar)
//   Same for SEC and CLOUD.
//
// Then define simulation scores referencing the parameter values:
// Example for Networking Onboard:
[PVI Sim Onboard Score - Networking] =
VAR EligibleBooking = [PVI Eligible Booking - Networking]
VAR SimOnboardBooking = 'Sim Onboard Booking NET'[Sim Onboard Booking NET Value]
VAR Ratio = DIVIDE( SimOnboardBooking, EligibleBooking )
VAR Score =
    MAXX(
        FILTER(
            PVI_Brackets,
            PVI_Brackets[Domain] = "Networking"
                && PVI_Brackets[Metric] = "Onboard"
                && PVI_Brackets[MinRatio] <= Ratio
        ),
        PVI_Brackets[Score]
    )
RETURN IF( EligibleBooking > 0, COALESCE(Score, 10), BLANK() )

// NOTE: Create equivalent measures for SEC and CLOUD, and for Adopt.
// Then create Sim Engagement Total = (Sim Onboard Score + Sim Adopt Score) / 2


// =============================================================================
// SECTION 4 — LIFECYCLE PAGE MEASURES
// =============================================================================
// Excel: SUMIFS(Booking Amount, Track=<offer>, Current stage=<stage>,
//               Maximum Incentive Deal Flag="Yes",
//               Booking Date > EDATE(TODAY()-DAY(TODAY())+1, -17))
//
// The Excel date logic: start of current calendar month minus 17 calendar months.
// DAX equivalent: use EDATE(DATE(YEAR(TODAY),MONTH(TODAY),1), -17)

[Lifecycle Booking by Stage] =
VAR CutoffDate =
    EDATE( DATE( YEAR(TODAY()), MONTH(TODAY()), 1 ), -17 )
RETURN
    CALCULATE(
        SUM( Data[Booking Amount - Net to Cisco] ),
        Data[Maximum Incentive Deal Flag] = "Yes",
        Data[Booking Date] > CutoffDate
    )

// Domain-level lifecycle booking (for portfolio-filtered charts)
[Lifecycle Booking - Networking] =
VAR CutoffDate = EDATE( DATE( YEAR(TODAY()), MONTH(TODAY()), 1 ), -17 )
RETURN
    CALCULATE(
        SUM( Data[Booking Amount - Net to Cisco] ),
        Data[Maximum Incentive Deal Flag] = "Yes",
        Data[Booking Date] > CutoffDate,
        Data[Deal CPI Portfolio] = "Networking"
    )

[Lifecycle Booking - Security] =
VAR CutoffDate = EDATE( DATE( YEAR(TODAY()), MONTH(TODAY()), 1 ), -17 )
RETURN
    CALCULATE(
        SUM( Data[Booking Amount - Net to Cisco] ),
        Data[Maximum Incentive Deal Flag] = "Yes",
        Data[Booking Date] > CutoffDate,
        Data[Deal CPI Portfolio] = "Security"
    )

[Lifecycle Booking - Cloud] =
VAR CutoffDate = EDATE( DATE( YEAR(TODAY()), MONTH(TODAY()), 1 ), -17 )
RETURN
    CALCULATE(
        SUM( Data[Booking Amount - Net to Cisco] ),
        Data[Maximum Incentive Deal Flag] = "Yes",
        Data[Booking Date] > CutoffDate,
        Data[Deal CPI Portfolio] = "Cloud + AI Infrastructure"
    )

[Lifecycle Booking - Collaboration] =
VAR CutoffDate = EDATE( DATE( YEAR(TODAY()), MONTH(TODAY()), 1 ), -17 )
RETURN
    CALCULATE(
        SUM( Data[Booking Amount - Net to Cisco] ),
        Data[Maximum Incentive Deal Flag] = "Yes",
        Data[Booking Date] > CutoffDate,
        Data[Deal CPI Portfolio] = "Collaboration"
    )

// Risk-level aggregates for the stacked bar chart
// High Risk = Purchase + Onboard stages
[Lifecycle Booking - High Risk] =
VAR CutoffDate = EDATE( DATE( YEAR(TODAY()), MONTH(TODAY()), 1 ), -17 )
RETURN
    CALCULATE(
        SUM( Data[Booking Amount - Net to Cisco] ),
        Data[Maximum Incentive Deal Flag] = "Yes",
        Data[Booking Date] > CutoffDate,
        Data[Current stage] IN { "Purchase", "Onboard" }
    )

// Medium Risk = Implement + Use stages
[Lifecycle Booking - Medium Risk] =
VAR CutoffDate = EDATE( DATE( YEAR(TODAY()), MONTH(TODAY()), 1 ), -17 )
RETURN
    CALCULATE(
        SUM( Data[Booking Amount - Net to Cisco] ),
        Data[Maximum Incentive Deal Flag] = "Yes",
        Data[Booking Date] > CutoffDate,
        Data[Current stage] IN { "Implement", "Use" }
    )

// Low Risk = Engage + Adopt + Completed stages
[Lifecycle Booking - Low Risk] =
VAR CutoffDate = EDATE( DATE( YEAR(TODAY()), MONTH(TODAY()), 1 ), -17 )
RETURN
    CALCULATE(
        SUM( Data[Booking Amount - Net to Cisco] ),
        Data[Maximum Incentive Deal Flag] = "Yes",
        Data[Booking Date] > CutoffDate,
        Data[Current stage] IN { "Engage", "Adopt", "Completed" }
    )


// =============================================================================
// SECTION 5 — CPI ADOPT PAGE MEASURES
// =============================================================================
// Excel source: Ref sheet rows 18-22, filtered by Portfolio+Offer dropdowns.
// All-time data (no date filter).

// ── Opt-in Ratio chart metrics ────────────────────────────────────────────────
// Eligible UC Payout: SUMIFS(Revised Max Incentive, MaxFlag="Yes", Stage="Eligible", Track)
[CPI Eligible UC Payout] =
CALCULATE(
    SUM( Data[Revised Maximum Incentive Amount] ),
    Data[Maximum Incentive Deal Flag] = "Yes",
    Data[Stage] = "Eligible"
)

// Opted-in Payout: same + Opt-In Status = "Opted In"
[CPI Opted-In Payout] =
CALCULATE(
    SUM( Data[Revised Maximum Incentive Amount] ),
    Data[Maximum Incentive Deal Flag] = "Yes",
    Data[Stage] = "Eligible",
    Data[Adopt Rebate Opt-In Status] = "Opted In"
)

// Potential (not yet opted-in) = Eligible - Opted-in
[CPI Potential Not-Yet-Opted-In] =
[CPI Eligible UC Payout] - [CPI Opted-In Payout]

// ── Incentives chart metrics ──────────────────────────────────────────────────
// Estimated Earned: SUMIFS(Est Earned, Track, MaxFlag="Yes", Opted In)
[CPI Estimated Earned] =
CALCULATE(
    SUM( Data[Estimated Earned Incentives] ),
    Data[Maximum Incentive Deal Flag] = "Yes",
    Data[Adopt Rebate Opt-In Status] = "Opted In"
)

// Potential Remaining: SUMIFS(Potential Incentives, Track, MaxFlag="Yes", Opted In, Eligible)
[CPI Potential Remaining] =
CALCULATE(
    SUM( Data[Potential Incentives] ),
    Data[Maximum Incentive Deal Flag] = "Yes",
    Data[Adopt Rebate Opt-In Status] = "Opted In",
    Data[Stage] = "Eligible"
)


// =============================================================================
// SECTION 6 — UTILITY MEASURES
// =============================================================================

// New Eligible count (for Overview or Details callout)
[New Eligible Count] =
CALCULATE(
    COUNTROWS( Data ),
    Data[New eligible] = TRUE()
)

// Expires within 3 months count
[Expiring Soon Count] =
CALCULATE(
    COUNTROWS( Data ),
    Data[Expires <3M?] = "Yes",
    Data[Stage] = "Eligible"
)
